### ISSUE TITLE
Mapa Mental-Web 3.0

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-yanet-02#1]
[MAPA MENTAL_WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-yanet-02/files/14540089/MAPA.MENTAL_WEB.3.0.pdf)

**Comment by Rufino07** [comment]
20/20 
muy bien echo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
